name: Test my API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    # - name: Set up Python ${{ matrix.python-version }}
    - uses: actions/setup-python@v3
      
    # - name: Install requirements.txt
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: BLACK
      run: |
        pip install black
        black --diff --check srs

    - name: ISORT
      run: |
        pip install isort
        isort --diff --check --profile black srs

    - name: MYPY
      run: |
        pip install mypy
        mypy srs

    - name: PYTEST
      run: |
        pip inctall pytest
        pytest test
            


      
        # pylint $(git ls-files '*.py')
