name: Test mod_30

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install requirements.txt
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pip install black
          
    - name: BLACK
      run: |
        black --diff --check module_30_ci_linters.homework.hw1.srs/
        
    # - name: ISORT
    #   run: |
    #     isort --diff --check --profile black srs/
        
    # - name: MYPY
    #   run: |
    #     mypy srs/
        
    # - name: PYTEST
    #   run: |
    #     pytest test/
