name: Test my API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
   
    # - name: Install requirements.txt
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: BLACK
    #   run: |
    #     pip install black
    #     black --diff --check $(git ls-files '*.py')

    # - name: ISORT
    #   run: |
    #     pip install isort
    #     isort --diff --check --profile black $(git ls-files '*.py')

    - name: MYPY
      run: |
        pip install mypy
        mypy $(git ls-files '*.py')
        
    # - name: FLAKE 8
    #   run: |
    #     # pip install flake8==4.0.1 flake8-bugbear==22.1.11 flake8-pie==0.15.0
    #     pip install flake8
    #     flake8 $(git ls-files '*.py')
        
    # - name: PYTEST
    #   run: |
    #     pip install pytest flask faker flask_sqlalchemy factory_boy
    #     pytest test
